const TOURS_ARR = [
    {
        name: "Mars",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        image: "/assets/mars_tours.png",
        price: 9586,
        code: 105,
    },
    {
        name: "Juno",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        image: "/assets/juno_tours.jpeg",
        price: 9586,
        code: 110,
    },
    {
        name: "Europa",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        image: "/assets/europa_tours.png",
        price: 9586,
        code: 115,
    },
    {
        name: "Jupiter",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        image: "/assets/jupiter_tours.png",
        price: 9586,
        code: 120,
    },
    {
        name: "Saturn",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        image: "/assets/saturn_tours.jpg",
        price: 9586,
        code: 125,
    },
    {
        name: "Uranus",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        image: "/assets/uranus_tours.jpg",
        price: 9586,
        code: 130,
    },
    {
        name: "Venus",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        image: "/assets/venus_tours.jpg",
        price: 9586,
        code: 135,
    },
    {
        name: "Mercury",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        image: "/assets/mercury_tours.jpg",
        price: 9586,
        code: 140,
    },
    {
        name: "Pluto",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        image: "/assets/pluto_tours.png",
        price: 9586,
        code: 145,
    },
];

/*const REWIEWS = [
    {
        code: 103,
        name: "С†ёР¶Р",
        photo: "/assets/comment_1.jpg",
        text: "РЁРёСЂРѕРєР°СЏ СЌР»РµРєС‚СЂРёС„РёРєР°С†РёСЏ СЋР¶РЅС‹С… РіСѓР±РµСЂРЅРёР№ РґР°СЃС‚ РјРѕС‰РЅС‹Р№ С‚РѕР»С‡РѕРє РїРѕРґСЉС‘РјСѓ СЃРµР»СЊСЃРєРѕРіРѕ С…РѕР·СЏР№СЃС‚РІР°.",
    },
    {
        code: 113,
        name: "¸Ñ¶Ð",
        photo: "/assets/comment_2.jpg",
        text: "Ð¨Ð¸Ñ€Ð¾ÐºÐ°Ñ ÑÐ»ÐµÐºÑ‚Ñ€Ð¸Ñ„Ð¸ÐºÐ°Ñ†Ð¸Ñ ÑŽÐ¶Ð½Ñ‹Ñ… Ð³ÑƒÐ±ÐµÑ€Ð½Ð¸Ð¹ Ð´Ð°ÑÑ‚ Ð¼Ð¾Ñ‰Ð½Ñ‹Ð¹ Ñ‚Ð¾Ð»Ñ‡Ð¾Ðº Ð¿Ð¾Ð´ÑŠÑ‘Ð¼Ñƒ ÑÐµÐ»ÑŒÑÐºÐ¾Ð³Ð¾ Ñ…Ð¾Ð·ÑÐ¹ÑÑ‚Ð²Ð°.",
    },
    {
        code: 123,
        name: "╝╚Г╝╙ ╞╝╓",
        photo: "/assets/comment_3.jpg",
        text: "≤╗Ю╝╙═О М╚╔╙БЮ╗Д╗╙═Ф╗О Н╕╜КЕ ёЦ║╔Ю╜╗╘ ╓═АБ ╛╝И╜К╘ Б╝╚Г╝╙ ╞╝╓ЙЯ╛Ц А╔╚ЛА╙╝ё╝ Е╝╖О╘АБ╒═.",
    },
    {
        code: 133,
        name: "Ð³ÑƒÐ±ÐµÑ€Ð½Ð¸Ð¹ ",
        photo: "/assets/comment_4.jpg",
        text: "Ð¨Ð¸Ñ€Ð¾ÐºÐ°Ñ ÑÐ»ÐµÐºÑ‚Ñ€Ð¸Ñ„Ð¸ÐºÐ°Ñ†Ð¸Ñ ÑŽÐ¶Ð½Ñ‹Ñ… Ð³ÑƒÐ±ÐµÑ€Ð½Ð¸Ð¹ Ð´Ð°ÑÑ‚ Ð¼Ð¾Ñ‰Ð½Ñ‹Ð¹ Ñ‚Ð¾Ð»Ñ‡Ð¾Ðº Ð¿Ð¾Ð´ÑŠÑ‘Ð¼Ñƒ ÑÐµÐ»ÑŒÑÐºÐ¾Ð³Ð¾ Ñ…Ð¾Ð·ÑÐ¹ÑÑ‚Ð²Ð°.",
    },
    {
        code: 143,
        name: "┘╚ ╟╒┬┼╥╬╔╩ ─┴╙╘",
        photo: "/assets/comment_5.jpg",
        text: "√╔╥╧╦┴╤ ▄╠┼╦╘╥╔╞╔╦┴├╔╤ └╓╬┘╚ ╟╒┬┼╥╬╔╩ ─┴╙╘ ═╧▌╬┘╩ ╘╧╠▐╧╦ ╨╧─▀г═╒ ╙┼╠╪╙╦╧╟╧ ╚╧┌╤╩╙╘╫┴.",
    },
    {
        code: 153,
        name: "î¦­ëå £ã¡",
        photo: "/assets/comment_6.jpg",
        text: "˜¨à®ª ï í«¥ªâà¨ä¨ª æ¨ï î¦­ëå £ã¡¥à­¨© ¤ áâ ¬®é­ë© â®«ç®ª ¯®¤êñ¬ã á¥«ìáª®£® å®§ï©áâ¢ .",
    },
    {
        code: 163,
        name: "Benedict",
        photo: "/assets/comment_7.jpg",
        text: "Nice",
    },
];*/

const CONTACTS = [
    {
        galaxy: "Milky Way",
        phone: "0145874524963896349659",
        email: "Juno@gabagaba.glob",
        adress: "17h 45m 40.0409s, −29° 0′ 28.118″",
        code: 107,
    },
    {
        galaxy: "Andromeda",
        phone: "••••− ••••• −•••• −−−•• ••••• ••−",
        email: "Juno@uabulabu.med",
        adress: "00h 42m 44.3s, +41° 16′ 9″",
        code: 117,
    },
    {
        galaxy: "Triangulum",
        phone: "||0000||00||0|||",
        email: "Juno@marsh.lum",
        adress: "01h 33m 50.9s, 30° 39′ 36″",
        code: 127,
    },
];

const COLORS = [
    "#000000",
    "#FFFFFF",
    "#FF0000",
    "#00FF00",
    "#0000FF",
    "#FFFF00",
    "#00FFFF",
    "#FF00FF",
    "#C0C0C0",
    "#808080",
    "#800000",
    "#808000",
    "#008000", 
    "#800080", 
    "#008080", 
    "#000080", 
    "#A52A2A", 
    "#DC143C", 
    "#FF7F50", 
    "#FF6347", 
    "#CD5C5C", 
    "#F08080", 
    "#E9967A", 
    "#FA8072", 
    "#FFA07A", 
    "#FF4500", 
    "#FF8C00", 
    "#FFA500", 
    "#FFD700", 
    "#DAA520", 
    "#EEE8AA", 
    "#BDB76B", 
    "#F0E68C", 
    "#808000", 
    "#9ACD32", 
    "#7CFC00",
    "#ADFF2F",
    "#008000",
    "#00FF00",
    "#32CD32",
    "#90EE90",
    "#00FA9A",
    "#00FF7F",
    "#66CDAA",
    "#20B2AA",
    "#2F4F4F",
    "#00FFFF",
    "#E0FFFF",
    "#00CED1",
    "#7FFFD4",
    "#4682B4",
    "#6495ED",
    "#1E90FF",
    "#87CEFA",
    "#191970",
    "#00008B",
    "#0000FF",
    "#8A2BE2",
    "#4B0082",
    "#483D8B",
    "#7B68EE",
    "#8B008B",
    "#9932CC",
    "#BA55D3",
    "#DDA0DD",
    "#EE82EE",
    "#FF00FF",
    "#C71585",
    "#FF1493",
    "#FF69B4",
    "#FFB6C1",
    "#FFE4C4",
];

export {TOURS_ARR, CONTACTS, COLORS}; 